---
name: oya
description: "OYA Pipeline Orchestration Dashboard"
author: "Lewis Prior <lewis@lewisandquark.com>"
version: "0.1.0"

# Plugin configuration
configuration:
  # OYA web server URL
  server_url:
    type: string
    default: "http://localhost:3000"
    description: "URL of the OYA web server API"

# UI configuration
ui:
  # Plugin can request specific pane size
  request_height: 10
  request_width: 80
