#!/usr/bin/env bash
# Generate Rust contract and Martin Fowler test plan for a bead

set -euo pipefail

BEAD_ID="${1:-}"
if [[ -z "$BEAD_ID" ]]; then
  echo "Usage: $0 <bead-id>" >&2
  exit 1
fi

CONTRACTS_DIR="/home/lewis/src/oya/.aya/contracts"
TESTS_DIR="/home/lewis/src/oya/.aya/test-plans"

# Create directories if needed
mkdir -p "$CONTRACTS_DIR" "$TESTS_DIR"

CONTRACT_FILE="$CONTRACTS_DIR/rust-contract-$BEAD_ID.md"
TESTS_FILE="$TESTS_DIR/martin-fowler-tests-$BEAD_ID.md"

# Check if files already exist
if [[ -f "$CONTRACT_FILE" ]]; then
  echo "Contract already exists: $CONTRACT_FILE" >&2
  exit 1
fi

# Get bead details
BEAD_INFO=$(br show "$BEAD_ID" 2>&1)
BEAD_TITLE=$(echo "$BEAD_INFO" | head -1 | sed 's/.*· //;s/   \[.*//')
BEAD_PRIORITY=$(echo "$BEAD_INFO" | grep -oP '\[● P\K\d' || echo "2")
BEAD_SIZE=$(echo "$BEAD_INFO" | grep -oP 'size:\K\w+' || echo "small")

# Generate timestamp
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

# Generate contract stub
cat > "$CONTRACT_FILE" << CONTRACT_EOF
# Rust Contract: $BEAD_TITLE

**Bead ID:** \`$BEAD_ID\`
**Priority:** P${BEAD_PRIORITY}
**Size:** ${BEAD_SIZE}
**Generated:** ${TIMESTAMP}
**Type:** Feature

## Overview

$(br show "$BEAD_ID" | sed -n '/#/,/^$/{/^#/!{/^$/!p}}')

## Functional Requirements

### Core Functionality

Based on the bead description above, implement the following:

\`\`\`rust
// Pseudo-code representation of API surface
// TODO: Fill in with actual function signatures based on requirements

\`\`\`

### Input/Output Specifications

| Input | Type | Validation | Output |
|-------|------|------------|--------|
| TODO  | TODO | TODO       | TODO   |

## Error Handling

### Error Types

\`\`\`rust
use thiserror::Error;

#[derive(Error, Debug)]
pub enum ContractError {
    #[error("TODO: Define error cases")]
    Todo,
}
\`\`\`

### Error Propagation Strategy

- **Zero panics**: All error paths use \`Result<T, E>\`
- **Zero unwraps**: Forbidden in production code
- **Railway-Oriented Programming**: Use \`?\` operator throughout

## Implementation Details

\`\`\`rust
// TODO: Add implementation details
\`\`\`

## Testing Requirements

See \`martin-fowler-tests-${BEAD_ID}.md\` for comprehensive test strategy.

## Integration Points

### Upstream Dependencies

- **TODO**: List dependencies

### Downstream Consumers

- **TODO**: List consumers

## Documentation Requirements

- [ ] Public API documentation
- [ ] Error handling guide
- [ ] Usage examples

## Non-Functional Requirements

### Reliability

- TODO: Define reliability requirements

### Maintainability

- TODO: Define maintainability requirements

### Security

- TODO: Define security requirements

## Acceptance Criteria

1. [ ] Core functionality implemented
2. [ ] Error handling for all failure modes
3. [ ] Zero panics, zero unwraps
4. [ ] All tests passing (see test plan)

---

*Generated by Architect Agent*
*Contract status: DRAFT - Needs completion*
CONTRACT_EOF

# Generate test plan stub
cat > "$TESTS_FILE" << TESTS_EOF
# Martin Fowler Test Plan: $BEAD_TITLE

**Bead ID:** \`$BEAD_ID\`
**Generated:** ${TIMESTAMP}
**Reference:** [Martin Fowler's Test Patterns](https://martinfowler.com/bliki/TestPyramid.html)
**Type:** Feature

## Test Strategy Overview

This test plan follows Martin Fowler's testing philosophy with a balanced test pyramid:
- **Unit tests**: Fast, isolated, numerous
- **Integration tests**: Slower, realistic interactions
- **End-to-end tests**: Slowest, critical paths only

## Test Categories

### 1. Unit Tests (70% of tests)

\`\`\`rust
#[cfg(test)]
mod unit_tests {
    use super::*;

    #[test]
    fn test_todo() {
        // TODO: Add unit tests
    }
}
\`\`\`

### 2. Integration Tests (20% of tests)

\`\`\`rust
#[cfg(test)]
mod integration_tests {
    use super::*;

    #[test]
    fn test_todo() {
        // TODO: Add integration tests
    }
}
\`\`\`

### 3. End-to-End Tests (10% of tests)

\`\`\`rust
#[test]
fn e2e_todo() {
    // TODO: Add E2E tests
}
\`\`\`

## Test Organization

\`\`\`
crates/<crate-name>/
├── tests/
│   ├── unit/                         # Pure logic tests
│   ├── integration/                  # Real I/O
│   └── e2e/                          # Full protocol tests
└── src/
    └── <module>.rs                   # Includes unit tests as mod tests
\`\`\`

## Test Execution

\`\`\`bash
# Unit tests only (fast feedback)
moon run :test-unit --package <crate-name>

# Integration tests
moon run :test-integration --package <crate-name>

# Full test suite
moon run :test --package <crate-name>
\`\`\`

## Acceptance Criteria

1. [ ] All unit tests passing (>90% coverage)
2. [ ] All integration tests passing
3. [ ] All E2E tests passing
4. [ ] Zero flaky tests (100% deterministic)

---

*Generated by Architect Agent*
*Test plan status: DRAFT - Needs completion*
TESTS_EOF

echo "Generated contract: $CONTRACT_FILE"
echo "Generated tests: $TESTS_FILE"
