cabal-version:   3.0
name:            pokemon-api
version:         0.1.0.0
license:         MIT
author:          Oya Pipeline
build-type:      Simple

executable pokemon-api
  main-is: Main.hs
  other-modules: Pokemon.Types
  build-depends:
    base >= 4.14 && < 5
    , aeson >= 2.0 && < 3
    , text >= 2.0 && < 3
